apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rodger-100/monitoring.git
    targetRevision: HEAD
    path: prom-grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: poc

  syncPolicy:
     syncOptions:
     - CreateNamespace=true

     automated:
       selfHeal: true
       prune: true    